### ISSUE TITLE
Add Support of Laravel 11

### ISSUE THREAD

**Issue by alexweb** [ranium/laravel-seedonce#21]
Please add support of Laravel 11

**Comment by riv-snst** [comment]
@abbasali @medeiroz @chiranjeeb-ranium  merge pls, really need it =)

**Comment by medeiroz** [comment]
I can't merge this, I don't have permissions to approve the githubflow

**Comment by abbasali** [comment]
On it!

**Comment by abbasali** [comment]
@alexweb Reviewed and added a comment [here](https://github.com/ranium/laravel-seedonce/pull/22#issuecomment-2041852211). Let's continue the discussion on the PR please. Thanks.
