### ISSUE TITLE
default directory of seeders has a wrong name and the comparisons between the seeders table and the class names is not usable 

### ISSUE THREAD

**Issue by MilesDPH** [ranium/laravel-seedonce#5]
I have noticed that in line 75 of the BaseCommand.php class it does not have the correct name of the seeders folder, so I could correct it this way 

`return Collection::make($this->laravel->databasePath().DIRECTORY_SEPARATOR.'seeders'.DIRECTORY_SEPARATOR)`

Also, when running the command, I realized that although there was already a record of seeders classes inside the seed table, the command php artisan seedonce: status kept showing me that no seed had been made, so I could fix it by modifying the following function inside Status.php 

/**
     * Get the status for the given seeded seeders
     *
     * @param  array  $seeded
     * @param  array  $availableSeeders
     * @return \Illuminate\Support\Collection
     */
    protected function getStatusFor(array $seeded, Collection $availableSeeders)
    {
        $seeded = collect($seeded)->map(function ($_seeded){
            return class_basename($_seeded);
        })->toArray();

        return Collection::make($availableSeeders)
                    ->map(function ($seeder) use ($seeded) {
                        return in_array($seeder, $seeded)
                                ? ['<info>Yes</info>', $seeder]
                                : ['<fg=red>No</fg=red>', $seeder];
                    });
    }

It is my first contribution to a third party package, so if I did something wrong let me know

**Comment by abbasali** [comment]
@MilesDPH Thanks for highlighting the issues. I believe the `seeds` folder has been renamed to `seeders` in Laravel 8 and hence the issue.

Can you please open a PR with your fixes? Note that it will be better to not hardcode the seed folder name and instead take it from a config value so that both `seeds` and `seeders` folder can work (as per config value set)

Thanks

**Comment by MilesDPH** [comment]
Thank you for your response, I have created a pull request with the change you have asked me, have a good day

**Comment by abbasali** [comment]
This has been addressed in PR https://github.com/ranium/laravel-seedonce/pull/8.
